- name: Terminate the ElasticSearch cluster
  hosts: localhost
  connection: localhost
  become: False
  vars:
    aws_region: us-east-1
    ec2_tags:
        role: ElasticSearch-Cluster
  tasks:
    - name: Find EC2 Facts
      ec2_instance_facts:
        region: "{{ aws_region }}"
        filters:
            "tag:role": ElasticSearch-Cluster
            "instance-state-name": running
      register: ec2_facts
      
      # , state={{item.state}}"
    - debug: 
        msg: "Instance {{ item.instance_id }} in state {{ item.state }}"
      with_items: "{{ ec2_facts.instances }}"
            
    - name: Terminate EC2 cluster
      ec2:
        region: "{{ aws_region }}"
        instance_ids: "{{ item.instance_id }}"
        state: absent
      with_items: "{{ ec2_facts.instances }}"
      